name: GitHub metrics as SVG image
on:
  schedule: [{cron: "0 22 * * *"}]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.TOKEN }}
          user: vittodevit
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_ignored: html, css
          plugin_languages_skipped: easymanage, uselesswebapp
          plugin_gists: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_music: yes
          plugin_music_limit: 5
          plugin_music_playlist: ${{ secrets.SPOTIFY_PLAYLIST }}
          