name: GitHub metrics as HTML Insights page
on:
  push:
    branches:
    - main
  schedule: [{cron: "0 22 * * *"}]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.TOKEN }}
          user: vittodevit
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Rome
          config_output: insights
          plugin_languages: yes
          plugin_languages_categories: programming
          plugin_languages_colors: github
          plugin_languages_ignored: html, css
          plugin_languages_skipped: easymanage, uselesswebapp, procr
          #plugin_languages_indepth: yes
          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_mode: mastered
          plugin_topics_limit: 0 
          plugin_gists: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_music: yes
          plugin_music_limit: 5
          plugin_music_playlist: https://open.spotify.com/embed/playlist/7FbN9PGwC0YXlE22CMjdKf
          config_output: insights
          